<a href="https://colab.research.google.com/github/Anushka-guptaa/localrepo/blob/main/Basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
# Reversing array 1.a)
arr = np.array([1, 2, 3, 6, 4, 5])
np.flip(arr)
#same for 2d array

array([5, 4, 6, 3, 2, 1])

In [7]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_arr = np.ravel(array1)

print("Original array:")
print(array1)
print("\nFlattened array:",flattened_arr)

Original array:
[[1 2 3]
 [2 4 5]
 [1 2 3]]

Flattened array: [1 2 3 2 4 5 1 2 3]


In [8]:
# Comparing determines whether they are equivalent by checking if every element at each index is the same.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = arr1 == arr2
equal_arrays = comparison.all()

print(equal_arrays)


True


In [9]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find the most frequent value using np.bincount + argmax
most_freq = np.bincount(x).argmax()

# Find the indices where this value occurs
indices = np.where(x == most_freq)[0]

print("Most frequent value:", most_freq)
print("Indices:", indices)

Most frequent value: 1
Indices: [0 5 7 8 9]


In [10]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# 1. Sum of all elements
total_sum = gfg.sum()

# 2. Row-wise sum (axis=1)
row_sum = gfg.sum(axis=1)

# 3. Column-wise sum (axis=0)
col_sum = gfg.sum(axis=0)

print("Total sum of elements:", total_sum)
print("Row-wise sum:\n", row_sum)
print("Column-wise sum:\n", col_sum)


Total sum of elements: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


In [11]:
n_array = np.array([
    [55, 25, 15],
    [30, 44, 2],
    [11, 45, 77]
])

# i. Sum of diagonal elements
diagonal_sum = np.trace(n_array)

# ii. Eigenvalues
eigen_values, eigen_vectors = np.linalg.eig(n_array)

# iii. Eigenvectors (already calculated above)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)

# v. Determinant
determinant = np.linalg.det(n_array)

print("Original Matrix:\n", n_array)
print("\nSum of Diagonal Elements:", diagonal_sum)
print("\nEigenvalues:\n", eigen_values)
print("\nEigenvectors:\n", eigen_vectors)
print("\nInverse of Matrix:\n", inverse_matrix)
print("\nDeterminant of Matrix:", determinant)


Original Matrix:
 [[55 25 15]
 [30 44  2]
 [11 45 77]]

Sum of Diagonal Elements: 176

Eigenvalues:
 [98.16835147 28.097044   49.73460452]

Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of Matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant of Matrix: 137180.0000000001


In [12]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
mul1 = np.dot(p1, q1)

# Covariance (each row is a variable, so transpose)
cov1 = np.cov(p1.T, q1.T)

print("Matrix Multiplication (2x2):\n", mul1)
print("\nCovariance:\n", cov1)


Matrix Multiplication (2x2):
 [[16 19]
 [26 31]]

Covariance:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


In [13]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
mul2 = np.dot(p2, q2)

# Covariance (each column is a variable)
combined = np.vstack((p2.T, q2))  # shape: (4, n)
cov2 = np.cov(combined)

print("Matrix Multiplication (3x2 * 2x3):\n", mul2)
print("\nCovariance:\n", cov2)


Matrix Multiplication (3x2 * 2x3):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance:
 [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [14]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product: pairwise dot products for each row
inner = np.inner(x, y)

# Outer product: flatten x and y first
outer = np.outer(x.flatten(), y.flatten())

# Cartesian product
cartesian = np.array([[i, j] for i in x.flatten() for j in y.flatten()])

print("Inner Product:\n", inner)
print("\nOuter Product:\n", outer)
print("\nCartesian Product:\n", cartesian)


Inner Product:
 [[17 52]
 [13 62]]

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [15]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)

# ii. Percentiles (flattened, by column, by row)
flattened = array.flatten()

percentile_flat = np.percentile(flattened, [25, 50, 75])
percentile_col = np.percentile(array, [25, 50, 75], axis=0)
percentile_row = np.percentile(array, [25, 50, 75], axis=1)

# iii. Mean, Median, Std
mean_flat = np.mean(flattened)
median_flat = np.median(flattened)
std_flat = np.std(flattened)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

# Output
print("Original Array:\n", array)
print("\nAbsolute Values:\n", abs_array)

print("\nPercentiles (Flattened 25, 50, 75):", percentile_flat)
print("Percentiles by Column:\n", percentile_col)
print("Percentiles by Row:\n", percentile_row)

print("\nMean (Flat):", mean_flat)
print("Median (Flat):", median_flat)
print("Std Dev (Flat):", std_flat)

print("\nMean by Column:", mean_col)
print("Median by Column:", median_col)
print("Std Dev by Column:", std_col)

print("\nMean by Row:", mean_row)
print("Median by Row:", median_row)
print("Std Dev by Row:", std_row)


Original Array:
 [[ 1 -2  3]
 [-4  5 -6]]

Absolute Values:
 [[1 2 3]
 [4 5 6]]

Percentiles (Flattened 25, 50, 75): [-3.5 -0.5  2.5]
Percentiles by Column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles by Row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Mean (Flat): -0.5
Median (Flat): -0.5
Std Dev (Flat): 3.8622100754188224

Mean by Column: [-1.5  1.5 -1.5]
Median by Column: [-1.5  1.5 -1.5]
Std Dev by Column: [2.5 3.5 4.5]

Mean by Row: [ 0.66666667 -1.66666667]
Median by Row: [ 1. -4.]
Std Dev by Row: [2.05480467 4.78423336]


In [16]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floors = np.floor(a)
ceils = np.ceil(a)
truncs = np.trunc(a)
rounded = np.round(a)

print("Original Array:\n", a)
print("\nFloor:\n", floors)
print("Ceiling:\n", ceils)
print("Truncated:\n", truncs)
print("Rounded:\n", rounded)


Original Array:
 [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]

Floor:
 [-2. -2. -1.  0.  1.  1.  3.]
Ceiling:
 [-1. -1. -0.  1.  2.  2.  3.]
Truncated:
 [-1. -1. -0.  0.  1.  1.  3.]
Rounded:
 [-2. -2. -0.  0.  2.  2.  3.]


In [17]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array (argsort returns original indices)
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_4 = np.sort(array)[:4]

# iv. 5 largest elements
largest_5 = np.sort(array)[-5:]

print("Original Array:", array)
print("Sorted Array:", sorted_array)
print("Indices of Sorted Array:", sorted_indices)
print("4 Smallest Elements:", smallest_4)
print("5 Largest Elements:", largest_5)

Original Array: [ 10  52  62  16  16  54 453]
Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


In [18]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
int_elements = array[array == array.astype(int)]

# ii. Float elements only (not whole numbers)
float_elements = array[array != array.astype(int)]

print("Original Array:", array)
print("Integer Elements Only:", int_elements)
print("Float (Non-Integer) Elements Only:", float_elements)


Original Array: [1.  1.2 2.2 2.  3.  2. ]
Integer Elements Only: [1. 2. 3. 2.]
Float (Non-Integer) Elements Only: [1.2 2.2]


In [19]:
pip install pillow


In [20]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)

    if len(img_array.shape) == 2:
        print("Grayscale image detected.")
    else:
        print("RGB image detected.")

    np.savetxt("image_data.txt", img_array.reshape(-1, img_array.shape[-1])
               if len(img_array.shape) == 3 else img_array, fmt='%d')

    print("Image data saved to image_data.txt")


In [21]:
# For grayscale:
grayscale_array = np.loadtxt("image_data.txt", dtype=int)

# For RGB (if reshaped flat during saving):
rgb_array = np.loadtxt("image_data.txt", dtype=int).reshape(height, width, 3)
# 🔺 You'll need to manually know the original height & width

print("Grayscale or RGB image array:\n", grayscale_array or rgb_array)


FileNotFoundError: image_data.txt not found.